set shell := ["powershell.exe", "-c"]

schemacode := "mindcode cs -l -c -s -a Cardillan -w --file-references windows-uri"
mindcode := "mindcode cm -l -d 3 -u source -s --file-references windows-uri"

schematics:
     {{schemacode}} overdrive-dome-schema.sdf
     {{schemacode}} overdrive-projector-schema.sdf

programs:
    {{mindcode}} overdrive-dome.mnd
    {{mindcode}} overdrive-projector.mnd

all:
    just schematics
    just programs
