set shell := ["powershell.exe", "-c"]

schemacode := "mindcode cs -l -c -s -a Cardillan -w --file-references windows-uri"
mindcode := "mindcode cm -l -d 3 -u source -s --file-references windows-uri"

schematics:
     {{schemacode}} impact-reactor-power-plant.sdf

programs:
    {{mindcode}} power-plant-reactor-control.mnd
    {{mindcode}} power-plant-battery-level.mnd
    {{mindcode}} power-plant-transport.mnd.mnd

all:
    just schematics
    just programs
