set shell := ["powershell.exe", "-c"]

schemacode := "mindcode cs -l -c -s -a Cardillan -w --file-references windows-uri"
mindcode := "mindcode cm -l -d 3 -u source -s --file-references windows-uri"

schematics:
    {{schemacode}} item-counter-micro-schema.sdf
    {{schemacode}} item-counter-schema.sdf
    {{schemacode}} item-rate-display-schema.sdf
    {{schemacode}} item-rate-meter-micro-schema.sdf
    {{schemacode}} item-rate-meter-schema.sdf
    {{schemacode}} level-display-schema.sdf
    {{schemacode}} level-meter-schema.sdf

programs:
    {{mindcode}} item-counter-micro.mnd
    {{mindcode}} item-counter.mnd
    {{mindcode}} item-rate-display.mnd
    {{mindcode}} item-rate-meter-init.mnd
    {{mindcode}} item-rate-meter-micro.mnd
    {{mindcode}} item-rate-meter.mnd
    {{mindcode}} level-display.mnd
    {{mindcode}} level-meter.mnd

all:
    just schematics
    just programs
