set shell := ["powershell.exe", "-c"]

schemacode := "mindcode cs -l -c -s -a Cardillan -w --file-references windows-uri --debug true"
mindcode := "mindcode cm -l -d 3 -u source -s --file-references windows-uri"

schematics:
     {{schemacode}} schematic.sdf

programs:
    {{mindcode}} BaseBuilder.mnd
    {{mindcode}} BuilderController.mnd
    {{mindcode}} CoreController.mnd
    {{mindcode}} Display.mnd
    {{mindcode}} FlareController.mnd
    {{mindcode}} Matrices.mnd
    {{mindcode}} Measurement.mnd
    {{mindcode}} MonoController.mnd
    {{mindcode}} OreLocator.mnd
    {{mindcode}} PolyController.mnd
    {{mindcode}} WorldProcHelper.mnd

all:
    just schematics
    just programs
