set shell := ["powershell.exe", "-c"]

schemacode := "mindcode cs -l -c -s -a Cardillan -w --file-references windows-uri"
mindcode := "mindcode cm -l -d 3 -u source -s --file-references windows-uri"

schematics:
     {{schemacode}} mandelbrot.sdf

programs:
    {{mindcode}} mandelbrot-compute.mnd
    {{mindcode}} mandelbrot-control.mnd

all:
    just schematics
    just programs
